{"uuid": "79feeb61-cced-41b9-ac99-a9ae3002d2de", "children": ["36192b80-7a8f-4bc8-9897-40f1df97f874", "39cc2852-21d2-4871-b209-ea4c174c4de9", "2ba3b93f-72d4-494b-8813-f1d2c552e132", "13911af3-b431-4f59-86f4-7fc9327257cb", "5fcc23b1-2ecc-47a7-857c-b41ffb14e14f", "6b1a51a3-1f6c-4c4a-9a1b-19e4a30fb4b4", "e34a9d78-4d8f-4a07-84c1-5ae0084b9dbd", "73fde73f-8275-4f26-8804-ed31423cded5", "492b7849-fb26-4f99-b78f-87b5b5f54600", "3f0f8415-a17c-46ab-9b60-01594979a2eb", "4df91921-e650-40f3-be70-ccbb097ef087", "c1df3022-b4b6-4030-bd80-6b28ff59aebf", "72fada6f-b86f-43e2-81f7-3c17b0b5a14b", "512fba6c-8981-4f07-9403-567fb342224e", "45138975-29c1-4900-9979-c56b5085cc77"], "befores": [{"name": "session_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x0074D343+3134275]\n\tOrdinal0 [0x0063A131+2007345]\n\tOrdinal0 [0x004DAEC8+569032]\n\tOrdinal0 [0x0045C9B7+51639]\n\tOrdinal0 [0x00480DFC+200188]\n\tOrdinal0 [0x00480C1D+199709]\n\tOrdinal0 [0x0047EB0B+191243]\n\tOrdinal0 [0x00462E77+77431]\n\tOrdinal0 [0x00463E3E+81470]\n\tOrdinal0 [0x00463DC9+81353]\n\tOrdinal0 [0x00650C99+2100377]\n\tGetHandleVerifier [0x008BB71A+1396954]\n\tGetHandleVerifier [0x008BB399+1396057]\n\tGetHandleVerifier [0x008C70E6+1444518]\n\tGetHandleVerifier [0x008BBCA8+1398376]\n\tOrdinal0 [0x00647F11+2064145]\n\tOrdinal0 [0x006522AB+2106027]\n\tOrdinal0 [0x006523D1+2106321]\n\tOrdinal0 [0x00664984+2181508]\n\tBaseThreadInitThunk [0x75F86359+25]\n\tRtlGetAppContainerNamedObjectPath [0x77AE7C24+228]\n\tRtlGetAppContainerNamedObjectPath [0x77AE7BF4+180]\n\n", "trace": "  File \"d:\\program files (x86)\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\program files (x86)\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\program files (x86)\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\seleniumweb\\saas\\TestCase\\lab_test\\conftest.py\", line 17, in session_login\n    driver = webdriver.Chrome(chromedriver)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 64, in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 79, in __init__\n    RemoteWebDriver.__init__(\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 183, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 280, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 349, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 240, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1601022579686, "stop": 1601022582701}], "start": 1601022579686, "stop": 1601022587457}