{"uuid": "e73c18ac-5c91-44f0-8575-62bafecb0cfd", "children": ["c2e41111-b7bc-4fa2-ab93-8d328435679c", "2c081516-8b03-4608-b852-733a6b249c97", "dca7a47a-63af-4c0d-87ea-8fb4d00c2af5", "01e0ec87-f2e0-429d-a08b-4c62eeefd30f", "a41817ff-8f9b-4884-9a97-bf1e57bab955", "990c808a-aa84-45be-8dfe-8c241b7cda6c", "929be722-9f3d-456c-9d77-21d51ff73a97"], "befores": [{"name": "project_session_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x0074D343+3134275]\n\tOrdinal0 [0x0063A131+2007345]\n\tOrdinal0 [0x004DAEC8+569032]\n\tOrdinal0 [0x0045C9B7+51639]\n\tOrdinal0 [0x00480DFC+200188]\n\tOrdinal0 [0x00480C1D+199709]\n\tOrdinal0 [0x0047EB0B+191243]\n\tOrdinal0 [0x00462E77+77431]\n\tOrdinal0 [0x00463E3E+81470]\n\tOrdinal0 [0x00463DC9+81353]\n\tOrdinal0 [0x00650C99+2100377]\n\tGetHandleVerifier [0x008BB71A+1396954]\n\tGetHandleVerifier [0x008BB399+1396057]\n\tGetHandleVerifier [0x008C70E6+1444518]\n\tGetHandleVerifier [0x008BBCA8+1398376]\n\tOrdinal0 [0x00647F11+2064145]\n\tOrdinal0 [0x006522AB+2106027]\n\tOrdinal0 [0x006523D1+2106321]\n\tOrdinal0 [0x00664984+2181508]\n\tBaseThreadInitThunk [0x75F86359+25]\n\tRtlGetAppContainerNamedObjectPath [0x77AE7C24+228]\n\tRtlGetAppContainerNamedObjectPath [0x77AE7BF4+180]\n\n", "trace": "  File \"d:\\program files (x86)\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\program files (x86)\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\program files (x86)\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\seleniumweb\\saas\\TestCase\\conftest.py\", line 34, in project_session_login\n    driver = webdriver.Chrome(chromedriver)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 64, in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 79, in __init__\n    RemoteWebDriver.__init__(\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 183, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 280, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 349, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\program files (x86)\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 240, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1601022584013, "stop": 1601022586936}], "start": 1601022584013, "stop": 1601022587452}